#!/bin/sh

set -eu

project_directory=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$project_directory"

if [ "$#" -eq 1 ] && [ "$1" = serve ]; then
  exec docker compose up
fi

exec docker compose run --rm escpost "$@"
