[package]
name = "escpost"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
description = "The most complete ESC/POS developer toolbox for receipt and label printers."
readme = "README.md"
keywords = ["escpos", "printer", "receipt", "cli", "pos"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "escpost"
path = "src/main.rs"

[dependencies]
axum.workspace = true
clap.workspace = true
directories.workspace = true
escpost-render = { version = "0.1.0", path = "../escpost-render" }
escpost-profiles = { version = "0.1.0", path = "../escpost-profiles" }
if-addrs.workspace = true
indicatif.workspace = true
inquire.workspace = true
nusb.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
webbrowser.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rustix.workspace = true

[lints]
workspace = true
