[package]
name = "escpost-python"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
escpost-render = { path = "../../crates/escpost-render" }
escpost-profiles = { path = "../../crates/escpost-profiles" }
pyo3.workspace = true

[lints]
workspace = true
